### ISSUE TITLE
Did part of a commit get missed?

### ISSUE THREAD

**Issue by epugh** [ogrodnek/java_fathom#1]
I noticed that the last commit says "removed ivy/ant build files, updated versions", but only the version was bumped!   Does the actual java code, if not the build scripts, work?   

However, what I really want to do is to do readability metrics using Spark...   Know anyone who has done that?

**Comment by ogrodnek** [comment]
I haven't worked on this in 10 years, but I just updated the build to maven.  `mvn build` as well as `mvn test` should work.

**Comment by epugh** [comment]
Thanks!

**Comment by ogrodnek** [comment]
Sure! Sorry for the multi-year delay :).

Let me know if you have any feedback, and I'd be happy to incorporate any PRs.

**Comment by epugh** [comment]
;-). Just tested, and it worked.   I may use this to generaate some interesting daataa for a talk on Apache Zeppelin...  thaanks.

**Comment by ogrodnek** [comment]
Sounds cool! Good luck and would love to hear how it goes.
